### ISSUE TITLE
Running any of the utils without options just hangs the program

### ISSUE THREAD

**Issue by bobhairgrove** [rgamble/csvutils#3]
If I do not supply command-line arguments to any of the utilities, the program just hangs without producing any output.

Expected behavior: either "help" or "usage" text should be output.

**Comment by rgamble** [comment]
All of the utility programs read from `stdin` if no output is provided (the source of the apparent hang) and all programs respond to the `--help` option as per GNU conventions.  `csvgrep`, `csvbreak`, and `csvcut` all emit a message and terminate when called without arguments.  `csvcount` is the CSV analogue to the Unix utility `wc`, neither of which emit a message if called with no arguments as this is a perfectly acceptable way to use the programs.  `csvcheck` and `csvfix` also read from `stdin` if no input is provided.  Exiting early from such valid invocations would require the use of a command-line argument to instruct the programs to read from `stdin` which doesn't seem necessary.  All of this is documented in the man pages and pdf documentation.

**Comment by bobhairgrove** [comment]
OK, sorry for the confusion on my part.
