### ISSUE TITLE
helper.c

### ISSUE THREAD

**Issue by bobhairgrove** [rgamble/csvutils#5]
I have some issues with the file **helper.c**:

1. Input should be `const` here, and the pointer needs to be checked:
```
void /* line 23 */
err (const char *msg) /* err (char *msg) */
{
  if (msg) fprintf(stderr, "%s\n", msg);
  exit(EXIT_FAILURE);
}
```

2. For this function:
```
int /* line 30 */
Is_numeric(char *s)
{
  /* Returns true if string consist entirely of digits */
  while (*s)
    if (!isdigit((int)(unsigned char)*(s++))) return 0;
  return 1;
}
```
I would prefer to see it done this way:
```
int
Is_numeric(const char *s)
{
  /* Returns true if string consist entirely of digits */
  int retval = 0;
  int c;
  if (s) {
    retval = 1;
    while ((c = (unsigned char)(*s++))) {
      if (!isdigit(c)) {
        retval = 0;
        break;
      }
    }
  }
  return retval;
}
```
3. For these two functions, input should be `const`. But why don't you just use the C library functions for this (`strdup`, `strndup`)???
```
char * /* line 39 */
Strdup(const char *s) /* Strdup(char *s) */
{
  char *tmp = xmalloc(strlen(s) + 1);
  strcpy(tmp, s);
  return tmp;
}

char * /* line 47 */
Strndup(const char *s, size_t len) /* Strndup(char *s, size_t len) */
{
  char *tmp = xmalloc(len + 1);
  memcpy(tmp, s, len);
  tmp[len] = '\0';
  return tmp;
}
```
4. This might break if input is not ASCII text (e.g. text in other languages besides English):
```
void /* line 56 */
Strupper(char *s)
{
  while (*s) {
    *s = toupper((int)(unsigned char)*s);
    s++;
  }
}
```

**Comment by rgamble** [comment]
Agreed for 1.

What is the benefit of the change for 2?

Agreed about the pointer to const parameters for 3.  `strdup` and `strndup` are not part of the Standard C library (they are POSIX extensions) but the reason for separate functions was probably to directly handle out-of-memory conditions without having to check explicitly at the call site for `ENOMEM` after each call.

Understood about 4 and this is a good point.  The documentation should either be updated to reflect this fact when using `-i` with `-F` or support for `-i` should be removed when using `-F`.  More importantly, `-i` does not seem to be honored when not using `-F` which probably deserves a separate ticket.

**Comment by bobhairgrove** [comment]
Hi Robert,

Thanks for the reply ... with no. 2, I guess the only benefit would be the pointer check. At first I thought both casts would be superfluous since a char which is a digit can never be negative, but the man page says undefined behavior for negative input except for EOF, so I put the cast to unsigned char back in. The alternative would be to declare the input parameter unsigned and let the caller do the cast.

I wasn't aware that `strdup` and `strndup` are not standard C library functions, but then again I don't do too much C programming -- mostly C++ where we are spared using these functions. :)

(BTW, when you get around to updating any documentation, you might check your email addresses in the docs which almost all of them still have the "sourceforge" address in there.)
